version: "3"
services:
  cache:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    
  server:
    build: .
    ports:
      - "4000:4000"
    # environment:
    #   DB_HOST: db
    #   DB_USER: user
    #   DB_PASSWORD: password
    #   DB_NAME: db
    #   DB_PORT: 5432

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
      args:
        - no_cache=1
    # environment:
    #   DB_HOST: db
    #   DB_USER: user
    #   DB_PASSWORD: password
    #   DB_NAME: db
    #   DB_PORT: 5432